[package]
name = "rust-http-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.26.2"
rustls = "0.22"
chrono = "0.4.41"
mime_guess = "2.0.5"